Repository Readme-Workflows/Readme-Icons, pull requests merged in 2021-05, with the labels that each got.

#2 Add wave gif
  README.md
  icons/wave/wave.gif
Labels: Priority: low, Status: Ready, Type: enhancement

#4 Use jsDelivr instead
  README.md
Labels: Priority: low, Status: Ready, Type: enhancement, Updates: documentation

#7 Add missing "Specific versions" section to ToC
  README.md
Labels: Action: No Changelog

#8 Fix missing Discord link in readme
  README.md
Labels: Action: No Changelog

#9 Added collaborator icon
  .prettierignore
  README.md
  icons/octicons/People.svg
Labels: Type: New Icon, Version: Patch

#10 Create LICENSE
  LICENSE
Labels: Action: No Changelog

#11 Add license
  LICENSE
Labels: Action: No Changelog

#12 Use a easy method to help folks
  README.md
Labels: Action: No Changelog
